kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gosrv
spec:
  host: gosrv.apps.testcluster.lab.local
  to:
    kind: Service
    name: gosrv
    weight: 100
  port:
    targetPort: 8080-tcp
